#ifndef __IPC_DEFS_H
#define __IPC_DEFS_H

#define MAX(a, b) ((a) > (b) ? (a) : (b))

#define GLOB_CHANNEL_READY_EVENT_POSTFIX L"__GLB_CH_RD_EVENT"
#define GLOB_SHARED_MEMORY_POSTFIX L"__GLB_SHR_MEM"
#define GLOB_CHANNEL_SEND_EVENT_POSTFIX L"__GLB_CH_SND_EVENT"
#define LOC_SHARED_MEMORY_POSTFIX L"__LOC_SHR_MEM"
#define LOC_CHANNEL_POSTFIX L"__LOC_CH"
#define LOC_CHANNEL_ANSWER_EVENT_POSTFIX L"__LOC_CH_ANSWR_EVENT"

#endif
